learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from webapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('webapp/',include('webapp.urls'))
]

learning_templates/webapp/urls.py
from django.urls import path
from webapp import views

#FOR TEMP TAGGING
app_name = 'web_application'


urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other')
]

learning_templates/webapp/models.py
from django.db import models

# Create your models here.

learning_templates/webapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello_world','number':100}
    return render(request,'webapp/index.html',context_dict)

def other(request):
    return render(request,'webapp/other.html')

def relative(request):
    return render(request,'webapp/relative.html')

learning_templates/webapp/templates/webapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="navbar-nav">d
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'web_application:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
      <div class="container">

        {% block body_block %}
        <!-- anything outside of this will be inherited if extended -->
        {% endblock %}

      </div>

  </body>
</html>

learning_templates/webapp/templates/webapp/index.html
<!DOCTYPE html>
{% extends "webapp/base.html" %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to Index</h1>
      <h1>This is index.html page showing!</h1>
      <!-- <h1>{{ text|upper }}</h1> -->
      <h1>{{ text|cut:"world" }}</h1>
      <!-- cuts any text that is added as argument -->
      <h1>{{ number|add:"99" }}</h1>
    </div>
  {% endblock %}

learning_templates/webapp/templates/webapp/other.html
<!DOCTYPE html>
{% extends "webapp/base.html" %}
  {% block body_block %}
    <h1>Welcome to Other</h1>
    <h2>This is an example of template inheritance!</h2>
  {% endblock %}

learning_templates/webapp/templates/webapp/relative.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to releative html</h1>
    <a href="{% url 'web_application:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>
  </body>
</html>